import { Conference } from '../types';

export const conferences: Conference[] = [
  {
    id: 1,
    title: 'React Summit 2024',
    description: 'O maior evento de React da América Latina',
    date: '2024-03-15',
    location: 'São Paulo, SP',
    spaces: 300,
    price: 799.9,
    category: 'Frontend',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 2,
    title: 'DevOps World',
    description: 'Conferência sobre as últimas tendências em DevOps',
    date: '2024-04-20',
    location: 'Rio de Janeiro, RJ',
    spaces: 200,
    price: 899.9,
    category: 'DevOps',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 3,
    title: 'Data Science Conference',
    description: 'Explorando o futuro da ciência de dados',
    date: '2024-05-10',
    location: 'Curitiba, PR',
    spaces: 250,
    price: 699.9,
    category: 'Data Science',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 4,
    title: 'AWS Community Day',
    description: 'Um dia inteiro dedicado à Amazon Web Services',
    date: '2024-06-05',
    location: 'Belo Horizonte, MG',
    spaces: 180,
    price: 499.9,
    category: 'Cloud',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 5,
    title: 'Python Brasil',
    description: 'A maior conferência Python do Brasil',
    date: '2024-07-15',
    location: 'Florianópolis, SC',
    spaces: 400,
    price: 599.9,
    category: 'Backend',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 6,
    title: 'Mobile Summit',
    description: 'Desenvolvimento mobile com React Native e Flutter',
    date: '2024-08-20',
    location: 'Salvador, BA',
    spaces: 220,
    price: 699.9,
    category: 'Mobile',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 7,
    title: 'Security Conference',
    description: 'Conferência sobre cybersegurança e ethical hacking',
    date: '2024-09-10',
    location: 'Brasília, DF',
    spaces: 150,
    price: 899.9,
    category: 'Security',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 8,
    title: 'UX/UI Design Week',
    description: 'Semana dedicada ao design de interfaces',
    date: '2024-10-05',
    location: 'Porto Alegre, RS',
    spaces: 200,
    price: 599.9,
    category: 'Design',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 9,
    title: 'Node.js Conference',
    description: 'Evento focado em Node.js e seu ecossistema',
    date: '2024-11-15',
    location: 'Recife, PE',
    spaces: 180,
    price: 649.9,
    category: 'Backend',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 10,
    title: 'AI & Machine Learning Summit',
    description: 'O futuro da inteligência artificial',
    date: '2024-12-01',
    location: 'São Paulo, SP',
    spaces: 300,
    price: 999.9,
    category: 'AI/ML',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 11,
    title: 'Vue.js Brazil',
    description: 'Conferência brasileira de Vue.js',
    date: '2024-03-25',
    location: 'Curitiba, PR',
    spaces: 200,
    price: 599.9,
    category: 'Frontend',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 12,
    title: 'Kubernetes Day',
    description: 'Tudo sobre orquestração de containers',
    date: '2024-04-15',
    location: 'Rio de Janeiro, RJ',
    spaces: 250,
    price: 799.9,
    category: 'DevOps',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 13,
    title: 'TypeScript Conference',
    description: 'Conferência dedicada ao TypeScript',
    date: '2024-05-20',
    location: 'São Paulo, SP',
    spaces: 220,
    price: 699.9,
    category: 'Frontend',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 14,
    title: 'GraphQL Summit',
    description: 'O maior evento de GraphQL do Brasil',
    date: '2024-06-10',
    location: 'Belo Horizonte, MG',
    spaces: 180,
    price: 649.9,
    category: 'Backend',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 15,
    title: 'IoT Conference',
    description: 'Internet das Coisas e suas aplicações',
    date: '2024-07-05',
    location: 'Porto Alegre, RS',
    spaces: 150,
    price: 749.9,
    category: 'IoT',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 16,
    title: 'Agile Brazil',
    description: 'Metodologias ágeis e gestão de projetos',
    date: '2024-08-15',
    location: 'Florianópolis, SC',
    spaces: 300,
    price: 599.9,
    category: 'Agile',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 17,
    title: 'Data Engineering Summit',
    description: 'Conferência sobre engenharia de dados',
    date: '2024-09-20',
    location: 'Salvador, BA',
    spaces: 200,
    price: 849.9,
    category: 'Data Science',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 18,
    title: 'Web Performance Conference',
    description: 'Otimização e performance web',
    date: '2024-10-10',
    location: 'Brasília, DF',
    spaces: 180,
    price: 599.9,
    category: 'Frontend',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 19,
    title: 'Blockchain Summit',
    description: 'O futuro da tecnologia blockchain',
    date: '2024-11-05',
    location: 'Recife, PE',
    spaces: 150,
    price: 899.9,
    category: 'Blockchain',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 20,
    title: 'Testing Conference',
    description: 'Conferência sobre testes e qualidade de software',
    date: '2024-12-15',
    location: 'São Paulo, SP',
    spaces: 200,
    price: 649.9,
    category: 'QA',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 21,
    title: 'Angular Brazil',
    description: 'O maior evento de Angular do país',
    date: '2024-03-30',
    location: 'Curitiba, PR',
    spaces: 250,
    price: 699.9,
    category: 'Frontend',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 22,
    title: 'Cloud Native Summit',
    description: 'Tecnologias cloud-native e microsserviços',
    date: '2024-04-25',
    location: 'Rio de Janeiro, RJ',
    spaces: 220,
    price: 849.9,
    category: 'Cloud',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 23,
    title: 'Game Dev Conference',
    description: 'Desenvolvimento de jogos e tecnologias relacionadas',
    date: '2024-05-15',
    location: 'São Paulo, SP',
    spaces: 180,
    price: 749.9,
    category: 'Game Dev',
    image: 'https://picsum.photos/400/300',
  },
  {
    id: 24,
    title: 'Accessibility Summit',
    description: 'Conferência sobre acessibilidade web',
    date: '2024-06-20',
    location: 'Belo Horizonte, MG',
    spaces: 150,
    price: 599.9,
    category: 'Accessibility',
    image: 'https://picsum.photos/400/300',
  },
];
